/**
 * JeuScreen.js  —  DinoCode
 *
 * Hosts the Blockly atelier inside a react-native-webview.
 *
 * Strategy: load HTML directly from a JS module (string export).
 *   assets/atelier/index.bundled.js is generated by `npm run prebuild:atelier`.
 *   It exports the self-contained HTML as a template-literal string.
 *   This is the most reliable approach on Android: no expo-asset, no
 *   file-system access, no localUri issues — just a plain JS string passed
 *   to <WebView source={{ html }} />.
 *
 * Bridge protocol:
 *   RN → WebView : postMessage({ type: 'charger_niveau', niveau })   (sent in onLoadEnd)
 *   WebView → RN : postMessage({ type: 'niveau_reussi', niveauId, ast })
 */

import React, { useRef, useState } from 'react';
import { View, StyleSheet, Text } from 'react-native';
import { WebView } from 'react-native-webview';

import niveaux from '../../levels';
import { enregistrerResultat } from '../storage/progression';
import { calculerEtoiles } from '../../core/etoiles';

// Bundled HTML string — generated by `npm run prebuild:atelier`
const ATELIER_HTML = require('../../assets/atelier/index.bundled.js');

export default function JeuScreen({ route, navigation }) {
  const niveauId = route.params.niveauId;
  const niveau = niveaux.find((n) => n.id === niveauId);
  const webRef = useRef(null);
  // erreur kept for future safety, but won't trigger now (sync require)
  const [erreur] = useState(false);

  function onLoadEnd() {
    if (!webRef.current || !niveau) return;
    webRef.current.postMessage(
      JSON.stringify({ type: 'charger_niveau', niveau })
    );
  }

  async function onMessage(event) {
    try {
      const msg = JSON.parse(event.nativeEvent.data);
      if (msg.type === 'niveau_reussi') {
        const etoiles = calculerEtoiles(niveau, msg.ast);
        await enregistrerResultat(niveau.id, etoiles, msg.ast.length);
        navigation.navigate('Carte', { vientDeReussir: niveau.id, etoiles });
      }
    } catch (e) {
      console.error('[JeuScreen] onMessage parse error:', e);
    }
  }

  if (erreur || !ATELIER_HTML) {
    return (
      <View style={styles.erreur}>
        <Text>😟 Impossible de charger l'atelier. Relance l'application.</Text>
      </View>
    );
  }

  return (
    <View style={styles.plein}>
      <WebView
        ref={webRef}
        originWhitelist={['*']}
        source={{ html: ATELIER_HTML }}
        onLoadEnd={onLoadEnd}
        onMessage={onMessage}
        javaScriptEnabled
        domStorageEnabled
        mixedContentMode="always"
      />
    </View>
  );
}

const styles = StyleSheet.create({
  plein: { flex: 1 },
  erreur: { flex: 1, justifyContent: 'center', alignItems: 'center' },
});
