/**
 * JeuScreen.js  —  Task 11 (Yoshi Code)
 *
 * Hosts the Blockly atelier inside a react-native-webview.
 *
 * Strategy: Option B — single self-contained inlined HTML.
 *   assets/atelier/index.bundled.html is generated by `npm run prebuild:atelier`
 *   (scripts/prebuild-atelier.js). It is a copy of webview/index.html where
 *   every <script src="..."> has been replaced by an inline <script> block.
 *   This means the WebView receives a single HTML string with no external
 *   dependencies, which is the only approach that works reliably on Android
 *   without native file-access permissions or complex asset-copy logic.
 *
 * Bridge protocol:
 *   RN → WebView : postMessage({ type: 'charger_niveau', niveau })   (sent in onLoadEnd)
 *   WebView → RN : postMessage({ type: 'niveau_reussi', niveauId, ast })
 */

import React, { useRef, useEffect, useState } from 'react';
import { View, StyleSheet, Text } from 'react-native';
import { WebView } from 'react-native-webview';
import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system';

import niveaux from '../../levels';
import { enregistrerResultat } from '../storage/progression';
import { calculerEtoiles } from '../../core/etoiles';

// The bundled HTML asset — Metro resolves this at build time.
// Run `npm run prebuild:atelier` before building to regenerate it.
// eslint-disable-next-line import/no-unresolved
const BUNDLED_HTML = require('../../assets/atelier/index.bundled.html');

export default function JeuScreen({ route, navigation }) {
  const niveauId = route.params.niveauId;
  const niveau = niveaux.find((n) => n.id === niveauId);
  const webRef = useRef(null);
  const [html, setHtml] = useState(null);
  const [erreur, setErreur] = useState(false);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        // expo-asset resolves the Metro asset module → a local file URI
        const asset = Asset.fromModule(BUNDLED_HTML);
        await asset.downloadAsync();
        const contenu = await FileSystem.readAsStringAsync(asset.localUri);
        if (!cancelled) setHtml(contenu);
      } catch (e) {
        console.error('[JeuScreen] failed to load bundled HTML:', e);
        if (!cancelled) setErreur(true);
      }
    })();
    return () => { cancelled = true; };
  }, []);

  function onLoadEnd() {
    if (!webRef.current || !niveau) return;
    webRef.current.postMessage(
      JSON.stringify({ type: 'charger_niveau', niveau })
    );
  }

  async function onMessage(event) {
    try {
      const msg = JSON.parse(event.nativeEvent.data);
      if (msg.type === 'niveau_reussi') {
        const etoiles = calculerEtoiles(niveau, msg.ast);
        await enregistrerResultat(niveau.id, etoiles, msg.ast.length);
        navigation.navigate('Carte', { vientDeReussir: niveau.id, etoiles });
      }
    } catch (e) {
      console.error('[JeuScreen] onMessage parse error:', e);
    }
  }

  // Show a friendly error if the bundled asset couldn't be loaded
  if (erreur) {
    return (
      <View style={styles.erreur}>
        <Text>😟 Impossible de charger l'atelier. Relance l'application.</Text>
      </View>
    );
  }

  // Show an empty screen while the asset is loading
  if (!html) return <View style={styles.plein} />;

  return (
    <View style={styles.plein}>
      <WebView
        ref={webRef}
        originWhitelist={['*']}
        // Option B: pass the entire self-contained HTML string directly.
        // No baseUrl needed — there are no external script references.
        source={{ html }}
        onLoadEnd={onLoadEnd}
        onMessage={onMessage}
        javaScriptEnabled
        // Standard bridge hardening
        domStorageEnabled
        // Silence mixed-content warnings (no network requests expected)
        mixedContentMode="always"
      />
    </View>
  );
}

const styles = StyleSheet.create({
  plein: { flex: 1 },
  erreur: { flex: 1, justifyContent: 'center', alignItems: 'center' },
});
